### ISSUE TITLE
Zeitzone

### ISSUE THREAD

**Issue by Logan-80** [philipkbh/home-assistant-vms-transport#2]
Hallo,

vielen Dank für diese super Erweiterung. Leider bekomme ich aktuell die Abfahrtzeiten mit einer Stunde Differenz wie auf dem Bild angezeigt.

![image](https://github.com/user-attachments/assets/41ec754c-e437-4814-a58a-db248c81200b)

Ich habe probiert die Wegzeit + 60 Minuten einzustellen, auch das funktioniert leider nicht.
Die Entitäten habe ich einmal über die configuration.yaml und einmal über die GUI hinzugefügt, beides mit dem selben Ergebniss.

Vielen Dank für den Support.

**Comment by philipkbh** [comment]
Welche Zeitzone hast du bei dir eingestellt?

**Comment by Logan-80** [comment]
Im Home Assistant GMT+1 Berlin
